NITACwpl/sports-fes-2023

src/components/Navbar.astro

liの終了タグなかったから追加

---

package-lock.json
package.json
src/components/SubTitle.astro
src/layouts/Layout.astro

✨ フォントをglobal cssにクラスとして指定しました

---

src/layouts/Layout.astro

💄 paddingとbgcolorの追加

---

src/components/DelayNewsItem.astro
src/components/contents/DelayNews.astro
src/layouts/Layout.astro

とりまマージだけお願いします。
CMS設置はmerge後のコミットで随時やっていくのでdelete branchしないように。

遅延情報のはりぼてを作りました。

---

src/components/Navbar.astro

- ここに書く
- ここに書く
- 
- ここに書く
- ここに書く
ここに書く
- ここに書く

naviレイアウト変更

---

package-lock.json
package.json
src/components/DelayNewsItem.astro
src/components/Navbar.astro
src/components/contents/Rulebook.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

アイコンが読み込まれないバグを修正

---

package-lock.json
src/components/SubTitle.astro
src/components/Title.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

Titleとかのスタイルを変更しましたFeature/style titles

---

src/components/Navbar.astro
src/layouts/Layout.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

♻️ color, font-sizeを変数にしました

---

src/components/FallAnimation.astro
src/components/contents/DelayNews.astro
src/components/contents/Rulebook.astro
src/layouts/Layout.astro
src/lib/fetchDelayNewsData.js

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

メニューとPDFと落ち葉の上下位置を調整しました

---

src/components/Navbar.astro
src/components/contents/DelayNews.astro
src/components/contents/News.astro
src/components/contents/PlaceMap.astro
src/components/contents/Rulebook.astro
src/components/contents/TimeTable.astro
src/components/contents/Tournament.astro
src/components/contents/Twitter.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

✨ menuからのジャンプを実装

---

src/components/BattleGroup.astro
src/components/TimeTableD2.astro
src/components/TimeTableItem/BadmintonD201.astro
src/components/TimeTableItem/BadmintonD202.astro
src/components/TimeTableItem/BasketD1B.astro
src/components/TimeTableItem/BasketD1F.astro
src/components/TimeTableItem/SoccerD1.astro
src/components/TimeTableItem/SoccerD2.astro
src/components/TimeTableItem/SoftD101.astro
src/components/TimeTableItem/SoftD102.astro
src/components/TimeTableItem/SoftD201.astro
src/components/TimeTableItem/SoftD202.astro
src/components/TimeTableItem/TableTennisD1A.astro
src/components/TimeTableItem/TableTennisD1B.astro
src/components/TimeTableItem/TennisD1B.astro
src/components/TimeTableItem/TennisD1C.astro
src/components/TimeTableItem/TennisD1F.astro
src/components/TimeTableItem/ValleyD2.astro
src/components/contents/DelayNews.astro
src/lib/fetchDelayNewsData.js
src/lib/fetchTimeTableData.js

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

タイムテーブルのCMS化を行いました

---

src/components/RuleModal.astro
src/components/contents/Rulebook.astro
src/components/rulePDF/Rule01.astro
src/components/rulePDF/Rule02.astro
src/components/rulePDF/Rule03.astro
src/components/rulePDF/Rule04.astro
src/components/rulePDF/Rule05.astro
src/components/rulePDF/Rule06.astro
src/components/rulePDF/Rule07.astro
src/components/rulePDF/Rule08.astro
src/components/rulePDF/Rule09.astro
src/components/rulePDF/Rule10.astro
src/components/rulePDF/Rule11.astro
src/components/rulePDF/Rule12.astro
src/components/rulePDF/Rule13.astro
src/components/rulePDF/Rule14.astro
src/components/rulePDF/Rule15.astro
src/components/rulePDF/Rule16.astro
src/components/rulePDF/Rule17.astro
src/components/rulePDF/Rule18.astro
src/components/rulePDF/Rule19.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

ルールブックも公開するよ💛確認してね

---

src/components/Navbar.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

navのaタグ範囲の変更とmenu閉じるときの動き変化

---

src/layouts/Layout.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

fix: 言語設定を日本語に変更した

---

src/components/BigSubTitle.astro
src/components/FallAnimationBadminton.astro
src/components/FallAnimationBasketball.astro
src/components/FallAnimationRopeRelay.astro
src/components/FallAnimationSoccer.astro
src/components/FallAnimationSoftball.astro
src/components/FallAnimationTableTennis.astro
src/components/FallAnimationTennis.astro
src/components/FallAnimationVolleyball.astro
src/components/Title.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

右上の検索ボタンを実装しました。

---

src/layouts/Layout.astro
src/layouts/LayoutBadminton.astro
src/layouts/LayoutBasketball.astro
src/layouts/LayoutRopeRelay.astro
src/layouts/LayoutSoccer.astro
src/layouts/LayoutSoftball.astro
src/layouts/LayoutTableTennis.astro
src/layouts/LayoutTennis.astro
src/layouts/LayoutVolleyball.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

📈 Google Analytics 4を設置しました

---

src/components/contents/PlaceMap.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

⚡️仮地図の中央ぞろえ

---

src/components/TimeTableItem/SoftD101.astro
src/components/TimeTableItem/SoftD102.astro
src/components/TimeTableItem/SoftD201.astro
src/components/TimeTableItem/SoftD202.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

🍻 ソフトボールの場所の名称をAbに変更

---

src/components/contents/News.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

newsのアイテムをスクロールできるようにしました

---

src/components/NewsItem.astro
src/components/contents/News.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

お知らせの修正 Fix/#64 reverse news

---

public/tournaments/tennis.svg

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

テニストーナメントのバグ修正！！！！

---

src/components/Navbar.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

フォームのリンクを追加

---

src/components/contents/Tournament.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

fix #76 バレーボールのトーナメントが男女で逆になっている問題を修正

---

src/components/NewsItem.astro

- ここに書く
- ここに書く
- ここに書く
- ここに書く
ここに書く
- ここに書く

インラインhtmlに変更
